version: '3.8'

services:
  nextflow:
    image: nextflow/nextflow:latest
    volumes:
      - ./workflows:/workflows
      - ./results:/results
    command: run main.nf
    environment:
      - NEXTFLOW_CONFIG=nextflow.config

  assembly_lr:
    build:
      context: ./docker
      dockerfile: dockerfile_assembly_lr
    image: assembly_lr

  assembly_sr:
    build:
      context: ./docker
      dockerfile: dockerfile_assembly_sr
    image: assembly_sr

  busco:
    image: ezlabgva/busco:v5.8.2_cv1
    container_name: busco_container
    user: "${UID}:${GID}" # Ensure correct permissions
    working_dir: /busco_wd
    volumes:
      - .:/busco_wd # Mount the current directory
    entrypoint: ["busco"] # Set BUSCO as the default command
