# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set environment variables to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Actualizar el sistema y instalar dependencias básicas
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    curl \
    git \
    perl \
    python3 \
    python3-pip \
    python3-dev \
    make \
    prodigal \
    hmmer \
    gcc \
    g++ \
    zlib1g-dev \
    libxml2-dev \
    libxslt1-dev \
    libpng-dev \
    libjpeg-dev \
    libsqlite3-dev \
    libperl-dev \
    libbz2-dev \
    liblzma-dev \
    libssl-dev \
    libgdbm-dev \
    libncurses5-dev \
    && apt-get clean

# Instalar antiSMASH
# Instalar antiSMASH
RUN git clone --depth 1 https://github.com/antismash/antismash.git /opt/antismash && \
    cd /opt/antismash && \
    python3 setup.py install

# Instalar Barrnap
RUN git clone https://github.com/tseemann/barrnap.git /opt/barrnap && \
    cd /opt/barrnap && \
    make


# Instalar MOB-suite
RUN git clone https://github.com/phac-nml/mob-suite.git /opt/mob-suite && \
    ls /opt/mob-suite && \
    cd /opt/mob-suite && \
    pip3 install .

# Set default command to open a bash shell
CMD ["/bin/bash"]
