# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set environment variables to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Actualizar el sistema y instalar dependencias básicas
RUN apt-get update && apt-get install -y \
    build-essential \
    zlib1g-dev \
    libpthread-stubs0-dev \
    wget \
    curl \
    git \
&& rm -rf /var/lib/apt/lists/*

# Instalar Kraken2
RUN wget https://github.com/DerrickWood/kraken2/archive/v2.1.2.tar.gz -O /tmp/kraken2.tar.gz && \
    tar -xzf /tmp/kraken2.tar.gz -C /opt && \
    cd /opt/kraken2-2.1.2 && \
    ./install_kraken2.sh /usr/local/bin && \
    rm -rf /tmp/kraken2.tar.gz

# Install Kaiju
RUN git clone https://github.com/bioinformatics-centre/kaiju.git && \
    cd kaiju/src && \
    make

# Set default command to open a bash shell
CMD ["/bin/bash"]
