# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set environment variables to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Actualizar el sistema y instalar dependencias básicas
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    curl \
    git \
    perl \
    python3 \
    python3-pip \
    python3-dev \
    make \
    prodigal \
    hmmer \
    gcc \
    g++ \
    zlib1g-dev \
    libxml2-dev \
    libxslt1-dev \
    libpng-dev \
    libjpeg-dev \
    libsqlite3-dev \
    libperl-dev \
    libbz2-dev \
    liblzma-dev \
    libssl-dev \
    libgdbm-dev \
    libncurses5-dev \
    && apt-get clean

# Instalar Kraken2
RUN wget https://github.com/DerrickWood/kraken2/archive/v2.1.2.tar.gz -O /tmp/kraken2.tar.gz && \
    tar -xzf /tmp/kraken2.tar.gz -C /opt && \
    cd /opt/kraken2-2.1.2 && \
    ./install_kraken2.sh /usr/local/bin && \
    rm -rf /tmp/kraken2.tar.gz

# Instalar Kaiju
RUN wget https://github.com/bioinformatics-centre/kaiju/archive/v1.9.0.tar.gz -O /tmp/kaiju.tar.gz && \
    tar -xzf /tmp/kaiju.tar.gz -C /opt && \
    cd /opt/kaiju-1.9.0/src && \
    make && \
    cp kaiju kaiju-mkbwt kaiju-addTaxonNames kaiju-convertNR kaiju-extractTaxa /usr/local/bin && \
    rm -rf /tmp/kaiju.tar.gz

# Verificar instalaciones
RUN kraken2 --version && \
    kaiju --version

# Set default command to open a bash shell
CMD ["/bin/bash"]
