# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set environment variables to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Actualizar e instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    wget curl git \
    build-essential \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libncurses5-dev \
    cmake \
    ncbi-blast+ \
    mummer \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Flye
RUN git clone https://github.com/fenderglass/Flye && cd Flye && python3 setup.py install

# Install dnaapler
RUN pip install dnaapler

# Install QUAST
RUN pip install quast

# Install Medaka
RUN pip install pyabpoa
RUN pip install --no-cache-dir --no-input --no-compile --use-deprecated=legacy-resolver \
    --index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    medaka-cpu --extra-index-url https://download.pytorch.org/whl/cpu

# Install bcftools, bgzip, minimap2, samtools, and tabix with specific versions
RUN wget https://github.com/samtools/bcftools/releases/download/1.11/bcftools-1.11.tar.bz2 && \
    tar -xjf bcftools-1.11.tar.bz2 && \
    cd bcftools-1.11 && ./configure && make && make install && cd .. && rm -rf bcftools-1.11*

RUN wget https://github.com/lh3/minimap2/releases/download/v2.11/minimap2-2.11_x64-linux.tar.bz2 && \
    tar -xjf minimap2-2.11_x64-linux.tar.bz2 && \
    mv minimap2-2.11_x64-linux/minimap2 /usr/local/bin/ && \
    chmod +x /usr/local/bin/minimap2 && \
    rm -rf minimap2-2.11_x64-linux*

RUN wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2 && \
    tar -xjf samtools-1.11.tar.bz2 && \
    cd samtools-1.11 && ./configure && make && make install && cd .. && rm -rf samtools-1.11*

RUN wget https://github.com/samtools/htslib/releases/download/1.11/htslib-1.11.tar.bz2 && \
    tar -xjf htslib-1.11.tar.bz2 && \
    cd htslib-1.11 && ./configure && make && make install && cd .. && rm -rf htslib-1.11*

# bgzip and tabix are included in htslib
RUN ln -s /usr/local/bin/bgzip /usr/bin/bgzip && \
    ln -s /usr/local/bin/tabix /usr/bin/tabix

# Crear un enlace simbólico para que 'python' apunte a 'python3'
RUN ln -s /usr/bin/python3 /usr/bin/python

# Set default command to open a bash shell
CMD ["bash"]
