# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set environment variables to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update and install system dependencies
RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    wget curl git \
    build-essential \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libncurses5-dev \
    cmake \
    ncbi-blast+ \
    docker.io \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Flye
RUN git clone https://github.com/fenderglass/Flye && cd Flye && python3 setup.py install

# Install dnaapler
RUN pip install dnaapler

# Install QUAST
RUN pip install quast

# Install Medaka
RUN pip install medaka-cpu

# Set up working directory
WORKDIR /busco_wd

# Set default command to open a bash shell
CMD ["bash"]
