# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set environment variables to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Actualizar e instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    wget curl git \
    build-essential \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libncurses5-dev \
    cmake \
    ncbi-blast+ \
    mummer \
    samtools \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Flye
RUN git clone https://github.com/fenderglass/Flye && cd Flye && python3 setup.py install

# Install dnaapler
RUN pip install dnaapler

# Install QUAST
RUN pip install quast

# Install Medaka
RUN pip install pyabpoa
RUN pip install --no-cache-dir --no-input --no-compile --use-deprecated=legacy-resolver \
    --index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    medaka-cpu --extra-index-url https://download.pytorch.org/whl/cpu

# Crear un enlace simbólico para que 'python' apunte a 'python3'
RUN ln -s /usr/bin/python3 /usr/bin/python

# Set default command to open a bash shell
CMD ["bash"]
