FROM ubuntu:latest

# Update the package lists
RUN apt-get update -y

# Install required dependencies
RUN apt-get install -y \
    curl \
    wget \
    git \
    make \
    cmake \
    build-essential \
    libstdc++6 \
    python3-pip

# Install Mamba
RUN pip3 install mamba

RUN mamba install -c conda-forge -c bioconda busco=5.8.2


# Set the default command to run BUSCO
CMD ["busco"]
