# Usa Ubuntu 22.04 como base
FROM ubuntu:22.04

# Configura la variable de entorno para evitar prompts en la instalación
ENV DEBIAN_FRONTEND=noninteractive

# Actualiza y instala las dependencias en un solo paso
RUN apt-get update && apt-get install -y \
    openjdk-11-jre \
    python3 python3-pip \
    wget curl git unzip \
    build-essential \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libncurses5-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instala Porechop
RUN git clone https://github.com/rrwick/Porechop.git /opt/Porechop && \
    cd /opt/Porechop && \
    python3 setup.py install && \
    rm -rf /opt/Porechop

# Instala NanoQC
RUN pip install nanoQC

#Descargar xvfb
RUN apt-get update && apt-get install -y xvfb

# Descarga e instala FastQC
RUN wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip -O /tmp/fastqc.zip && \
    unzip /tmp/fastqc.zip -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/FastQC/fastqc && \
    ln -s /usr/local/bin/FastQC/fastqc /usr/local/bin/fastqc && \
    rm /tmp/fastqc.zip

# Agrega FastQC al PATH
ENV PATH="/usr/local/bin/FastQC:$PATH"

# Instala htslib
RUN wget https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2 -O /tmp/htslib.tar.bz2 && \
    tar -xjf /tmp/htslib.tar.bz2 -C /tmp && \
    cd /tmp/htslib-1.17 && \
    ./configure && make && make install && \
    rm -rf /tmp/htslib*

# Instala Falco
RUN wget https://github.com/smithlabcode/falco/releases/download/v1.2.5/falco-1.2.5.tar.gz -O /tmp/falco.tar.gz && \
    tar -xzf /tmp/falco.tar.gz -C /tmp && \
    cd /tmp/falco-1.2.5 && \
    ./configure && make && make install && \
    rm -rf /tmp/falco*

# Comando por defecto: bash interactivo
CMD ["/bin/bash"]
